services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    env_file:
      - .env
  server:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    # command: npx prisma migrate dev --name init
